---

- name: Download Minecraft software
  get_url: url='http://overviewer.org/builds/deb64/1/overviewer-0.12.93.deb' dest='/tmp/'

- name: Create overviewer group
  group: name=overviewer

- name: Create overviewer user
  user: name=overviewer comment="minecraft overviwer user" group=overviewer

- name: create data directory
  file: path=/home/overviewer/data state=directory mode=0755 owner=overviewer group=overviewer

- name: create render directory
  file: path=/home/overviewer/render state=directory mode=0755 owner=overviewer group=overviewer

- name: create .minecraft directory
  file: path=/home/overviewer/.minecraft/versions/1.10.2 state=directory mode=0755 owner=overviewer group=overviewer

- name: Download map textures
  get_url: url='https://s3.amazonaws.com/Minecraft.Download/versions/1.10.2/1.10.2.jar' dest='/home/overviewer/.minecraft/versions/1.10.2/1.10.2.jar'

- name: Install Overviewer repo
  apt: deb='/tmp/overviewer-0.12.93.deb'

- name: Delete overviewer deb file
  file: path=/tmp/overviewer-0.12.93.deb state=absent

- name: Install Overviewer
  apt: name=minecraft-overviewer state=installed

- name: Copy Overviewer Configuration
  copy: src=overviewer.cfg dest=/home/overviewer/overviewer.cfg owner=overviewer group=overviewer
