---

- name: Create Minecraft group
  group: name=minecraft

- name: Create Minecraft user
  user: name=minecraft comment="minecraft user" group=minecraft

- name: Create Minecraft application directory
  file: path=/home/minecraft/app state=directory owner=minecraft group=minecraft state=directory

- name: Download Minecraft software
  get_url: url='https://s3.amazonaws.com/Minecraft.Download/versions/{{ minecraft.version }}/minecraft_server.{{ minecraft.version }}.jar' dest='/home/minecraft/app'

- name: Accept Minecraft EULA
  copy: src=eula.txt dest=/home/minecraft/app/eula.txt owner=minecraft group=minecraft

- name: Server Properties
  copy: src=server.properties dest=/home/minecraft/app/server.properties owner=minecraft group=minecraft

- name: Add banned-ips list
  copy: src=banned-ips.json dest=/home/minecraft/app/banned-ips.json owner=minecraft group=minecraft

- name: Add banned-players list
  copy: src=banned-players.json dest=/home/minecraft/app/banned-players.json owner=minecraft group=minecraft

- name: Add ops list
  copy: src=ops.json dest=/home/minecraft/app/ops.json owner=minecraft group=minecraft

- name: Add whitelist
  copy: src=whitelist.json dest=/home/minecraft/app/whitelist.json owner=minecraft group=minecraft

- name: Install Minecraft systemd script
  copy: src=minecraft.service dest=/etc/systemd/system/minecraft.service owner=root group=root mode=0644

- name: Reload daemon script
  systemd: daemon_reload: yes
  name: minecraft
  state: restarted

- name: PostRouting 25565 to 443
  iptables:
    table: nat
    chain: PREROUTING
    in_interface: eth0
    protocol: tcp
    match: tcp
    destination_port: 443
    jump: REDIRECT
    to_port: 25565
  become: yes

- name: PostRouting 25565 to 443
  iptables:
    table: nat
    chain: PREROUTING
    in_interface: eth0
    protocol: tcp
    match: tcp
    destination_port: 80
    jump: REDIRECT
    to_port: 25565
  become: yes
