- name: Delete Minecraft Node
  gather_facts: False
  connection: local
  hosts: localhost
  tasks:
    - name: Delete Minecraft Node
      local_action:
        module: rax
        credentials: ~/.rackspace_cloud_credentials
        name: "{{ config.node_name }}-{{ item.value.region }}-%02d"
        exact_count: yes
        flavor: performance1-2
        image: ubuntu-1604-lts-xenial-xerus-pvhvm
        region: "{{ item.value.region }}"
        wait: yes
        state: absent
        group: mc
        count: "{{ item.value.node_count }}"
        files:
           /root/.ssh/authorized_keys: ~/.ssh/id_rsa.pub
        networks:
           - private
           - public
      with_dict: minecraft_opts
      register: rax
