- name: Delete Minecraft Map Node
  gather_facts: False
  connection: local
  hosts: localhost
  tasks:
    - name: Deleting Minecraft Map Node
      local_action:
        module: rax
        credentials: ~/.rackspace_cloud_credentials
        name: "{{ webconfig.node_name }}-{{ web_opts.region }}-%02d"
        exact_count: yes
        flavor: General1-8
        image: ubuntu-1604-lts-xenial-xerus-pvhvm
        region: "{{ web_opts.region }}"
        wait: yes
        state: absent
        group: web
        count: "{{ web_opts.node_count }}"
        files:
           /root/.ssh/authorized_keys: ~/.ssh/id_rsa.pub
        networks:
           - private
           - public
      register: rax
