- name: Build Minecraft Map Node
  gather_facts: False
  connection: local
  hosts: localhost
  tasks:
    - name: Build Minecraft Map Node
      local_action:
        module: rax
        credentials: ~/.rackspace_cloud_credentials
        name: "{{ webconfig.node_name }}-{{ web_opts.region }}-%02d"
        exact_count: yes
        flavor: Performance1-8
        image: ubuntu-1604-lts-xenial-xerus-pvhvm
        region: "{{ web_opts.region }}"
        wait: yes
        state: present
        group: web
        count: "{{ web_opts.node_count }}"
        files:
           /root/.ssh/authorized_keys: ~/.ssh/id_rsa.pub
        networks:
           - private
           - public
      with_dict: web_opts
      register: rax

    - name: Add created servers to Minecraft web group
      local_action:
        module: add_host
        hostname: "{{ item.name }}"
        ansible_user: root
        ansible_ssh_host: "{{ item.rax_accessipv4 }}"
        ansible_ssh_pass: "{{ item.rax_adminpass }} "
        group: web
